spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  application:
    name: NoticeBoard
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3305/NoticeBoardSpring?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
    sql-script-encoding: UTF-8
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
handlebars:
  expose-request-attributes: true
  expose-session-attributes: true

